{
//=========Macro generated from canvas: canvasbtag_morethanzero_DiMuon_375_475/Btag_Pre_AlphaT_5__all/cannameBtag_Pre_AlphaT_5__all
//=========  (Thu May 10 12:47:00 2012) by ROOT version5.32/00
   TCanvas *canvasbtag_morethanzero_DiMuon_375_475/Btag_Pre_AlphaT_5__all = new TCanvas("canvasbtag_morethanzero_DiMuon_375_475/Btag_Pre_AlphaT_5__all", "cannameBtag_Pre_AlphaT_5__all",1,1,1200,1176);
   gStyle->SetOptStat(0);
   canvasbtag_morethanzero_DiMuon_375_475/Btag_Pre_AlphaT_5__all->SetHighLightColor(2);
   canvasbtag_morethanzero_DiMuon_375_475/Btag_Pre_AlphaT_5__all->Range(0,0,1,1);
   canvasbtag_morethanzero_DiMuon_375_475/Btag_Pre_AlphaT_5__all->SetFillColor(0);
   canvasbtag_morethanzero_DiMuon_375_475/Btag_Pre_AlphaT_5__all->SetBorderMode(0);
   canvasbtag_morethanzero_DiMuon_375_475/Btag_Pre_AlphaT_5__all->SetBorderSize(2);
   canvasbtag_morethanzero_DiMuon_375_475/Btag_Pre_AlphaT_5__all->SetTickx(1);
   canvasbtag_morethanzero_DiMuon_375_475/Btag_Pre_AlphaT_5__all->SetTicky(1);
   canvasbtag_morethanzero_DiMuon_375_475/Btag_Pre_AlphaT_5__all->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: u
   TPad *u = new TPad("u", "u",0.01,0.25,0.99,0.99);
   u->Draw();
   u->cd();
   u->Range(-0.7500001,-0.6550936,6.75,2.885543);
   u->SetFillColor(0);
   u->SetBorderMode(0);
   u->SetBorderSize(2);
   u->SetLogy();
   u->SetTickx(1);
   u->SetTicky(1);
   u->SetFrameBorderMode(0);
   u->SetFrameBorderMode(0);
   Double_t xAxis3864[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis3864);
   Btag_Pre_AlphaT_5__all->SetBinContent(2,34);
   Btag_Pre_AlphaT_5__all->SetBinContent(3,8);
   Btag_Pre_AlphaT_5__all->SetBinContent(4,1);
   Btag_Pre_AlphaT_5__all->SetBinError(2,5.830952);
   Btag_Pre_AlphaT_5__all->SetBinError(3,3.03);
   Btag_Pre_AlphaT_5__all->SetBinError(4,1);
   Btag_Pre_AlphaT_5__all->SetMinimum(0.5);
   Btag_Pre_AlphaT_5__all->SetMaximum(340);
   Btag_Pre_AlphaT_5__all->SetEntries(43);
   Btag_Pre_AlphaT_5__all->SetLineWidth(2);
   Btag_Pre_AlphaT_5__all->SetMarkerStyle(20);
   Btag_Pre_AlphaT_5__all->SetMarkerSize(1.5);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("N_{b-tag}");
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitleOffset(1.3);
   Btag_Pre_AlphaT_5__all->Draw("");
   Double_t xAxis3865[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis3865);
   Btag_Pre_AlphaT_5__all->SetLineColor(5);
   Btag_Pre_AlphaT_5__all->SetLineWidth(3);
   Btag_Pre_AlphaT_5__all->SetMarkerStyle(20);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("Number of Btags");
   Btag_Pre_AlphaT_5__all->Draw("SAMEHIST");
   
   THStack * = new THStack();
   ->SetName("");
   ->SetTitle("");
   
   TH1F *_stack_258 = new TH1F("_stack_258","",6,0,6);
   _stack_258->SetMinimum(0.01341977);
   _stack_258->SetMaximum(53.67906);
   _stack_258->SetDirectory(0);
   _stack_258->SetStats(0);
   _stack_258->GetXaxis()->SetLabelFont(42);
   _stack_258->GetXaxis()->SetLabelOffset(0.007);
   _stack_258->GetXaxis()->SetLabelSize(0.05);
   _stack_258->GetXaxis()->SetTitleSize(0.05);
   _stack_258->GetYaxis()->SetLabelFont(42);
   _stack_258->GetYaxis()->SetLabelOffset(0.007);
   _stack_258->GetYaxis()->SetLabelSize(0.05);
   _stack_258->GetZaxis()->SetLabelFont(42);
   _stack_258->GetZaxis()->SetLabelOffset(0.007);
   _stack_258->GetZaxis()->SetLabelSize(0.05);
   ->SetHistogram(_stack_258);
   
   Double_t xAxis3866[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis3866);
   Btag_Pre_AlphaT_5__all->SetBinContent(2,29.80901);
   Btag_Pre_AlphaT_5__all->SetBinContent(3,11.20886);
   Btag_Pre_AlphaT_5__all->SetBinContent(4,0.7423755);
   Btag_Pre_AlphaT_5__all->SetBinError(2,3.740401);
   Btag_Pre_AlphaT_5__all->SetBinError(3,2.062739);
   Btag_Pre_AlphaT_5__all->SetBinError(4,0.5372512);
   Btag_Pre_AlphaT_5__all->SetEntries(183);
   Btag_Pre_AlphaT_5__all->SetLineColor(3);
   Btag_Pre_AlphaT_5__all->SetLineWidth(3);
   Btag_Pre_AlphaT_5__all->SetMarkerColor(3);
   Btag_Pre_AlphaT_5__all->SetMarkerStyle(20);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("Number of Btags");
   ->Add(Btag_Pre_AlphaT_5__all,"");
   Double_t xAxis3867[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis3867);
   Btag_Pre_AlphaT_5__all->SetLineColor(7);
   Btag_Pre_AlphaT_5__all->SetLineStyle(10);
   Btag_Pre_AlphaT_5__all->SetLineWidth(3);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("Number of Btags");
   ->Add(Btag_Pre_AlphaT_5__all,"");
   ->Draw("samehist");
   
   TLegend *leg = new TLegend(0.68,0.53,0.9,0.75,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.02);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("Btag_Pre_AlphaT_5__all","Data","P");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.5);
   entry=leg->AddEntry("Btag_Pre_AlphaT_5__all","Zinv","L");
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Btag_Pre_AlphaT_5__all","Combined EWK","L");
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Btag_Pre_AlphaT_5__all","QCD","L");
   entry->SetLineColor(7);
   entry->SetLineStyle(10);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TLatex *   tex = new TLatex(0.1,0.95,"btag_morethanzero_DiMuon_375_475    Jet Multiplicity=all");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.6,0.85,"CMS Preliminary 2012, 7TeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.6,0.79,"\int L dt = 5.0 fb^{-1}");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis3868[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis3868);
   Btag_Pre_AlphaT_5__all->SetBinContent(2,34);
   Btag_Pre_AlphaT_5__all->SetBinContent(3,8);
   Btag_Pre_AlphaT_5__all->SetBinContent(4,1);
   Btag_Pre_AlphaT_5__all->SetBinError(2,5.830952);
   Btag_Pre_AlphaT_5__all->SetBinError(3,3.03);
   Btag_Pre_AlphaT_5__all->SetBinError(4,1);
   Btag_Pre_AlphaT_5__all->SetMinimum(0.5);
   Btag_Pre_AlphaT_5__all->SetMaximum(340);
   Btag_Pre_AlphaT_5__all->SetEntries(43);
   Btag_Pre_AlphaT_5__all->SetLineWidth(2);
   Btag_Pre_AlphaT_5__all->SetMarkerStyle(20);
   Btag_Pre_AlphaT_5__all->SetMarkerSize(1.5);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("N_{b-tag}");
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitleOffset(1.3);
   Btag_Pre_AlphaT_5__all->Draw("PSAME");
   u->Modified();
   canvasbtag_morethanzero_DiMuon_375_475/Btag_Pre_AlphaT_5__all->cd();
  
// ------------>Primitives in pad: d
   d = new TPad("d", "d",0.01,0.01,0.99,0.25);
   d->Draw();
   d->cd();
   d->Range(-0.7500001,-0.25,6.75,2.25);
   d->SetFillColor(0);
   d->SetBorderMode(0);
   d->SetBorderSize(2);
   d->SetTickx(1);
   d->SetTicky(1);
   d->SetFrameBorderMode(0);
   d->SetFrameBorderMode(0);
   Double_t xAxis3869[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis3869);
   Btag_Pre_AlphaT_5__all->SetBinContent(2,1.140595);
   Btag_Pre_AlphaT_5__all->SetBinContent(3,0.713721);
   Btag_Pre_AlphaT_5__all->SetBinContent(4,1.347027);
   Btag_Pre_AlphaT_5__all->SetBinError(2,0.2125011);
   Btag_Pre_AlphaT_5__all->SetBinError(3,0.4210911);
   Btag_Pre_AlphaT_5__all->SetBinError(4,1.234395);
   Btag_Pre_AlphaT_5__all->SetMinimum(0);
   Btag_Pre_AlphaT_5__all->SetMaximum(2);
   Btag_Pre_AlphaT_5__all->SetEntries(3.517197);
   Btag_Pre_AlphaT_5__all->SetLineWidth(2);
   Btag_Pre_AlphaT_5__all->SetMarkerStyle(20);
   Btag_Pre_AlphaT_5__all->SetMarkerSize(1.5);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetLabelSize(0.12);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitleOffset(1.3);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetTitle("Data/MC");
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetNdivisions(505);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetLabelSize(0.11);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetTitleSize(0.1);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetTitleOffset(0.5);
   Btag_Pre_AlphaT_5__all->Draw("P");
   
   TGraphErrors *gre = new TGraphErrors(6);
   gre->SetName("Graph_from_Btag_Pre_AlphaT_5__all");
   gre->SetTitle("");
   gre->SetFillColor(17);
   gre->SetFillStyle(3244);
   gre->SetLineWidth(2);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.5);
   gre->SetPoint(0,0.5,1);
   gre->SetPointError(0,0.5,0);
   gre->SetPoint(1,1.5,1);
   gre->SetPointError(1,0.5,0.1254788);
   gre->SetPoint(2,2.5,1);
   gre->SetPointError(2,0.5,0.1840275);
   gre->SetPoint(3,3.5,1);
   gre->SetPointError(3,0.5,0.723692);
   gre->SetPoint(4,4.5,1);
   gre->SetPointError(4,0.5,0);
   gre->SetPoint(5,5.5,1);
   gre->SetPointError(5,0.5,0);
   
   TH1F *Graph_Graph_from_Btag_Pre_AlphaT_5__all645 = new TH1F("Graph_Graph_from_Btag_Pre_AlphaT_5__all645","",100,0,6.6);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all645->SetMinimum(0.1315696);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all645->SetMaximum(1.86843);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all645->SetDirectory(0);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all645->SetStats(0);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all645->GetXaxis()->SetLabelFont(42);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all645->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all645->GetXaxis()->SetLabelSize(0.05);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all645->GetXaxis()->SetTitleSize(0.05);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all645->GetYaxis()->SetLabelFont(42);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all645->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all645->GetYaxis()->SetLabelSize(0.05);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all645->GetZaxis()->SetLabelFont(42);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all645->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all645->GetZaxis()->SetLabelSize(0.05);
   gre->SetHistogram(Graph_Graph_from_Btag_Pre_AlphaT_5__all645);
   
   gre->Draw("2");
   TLine *line = new TLine(0,1,6,1);
   line->SetLineWidth(3);
   line->Draw();
   Double_t xAxis3870[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis3870);
   Btag_Pre_AlphaT_5__all->SetBinContent(2,1.140595);
   Btag_Pre_AlphaT_5__all->SetBinContent(3,0.713721);
   Btag_Pre_AlphaT_5__all->SetBinContent(4,1.347027);
   Btag_Pre_AlphaT_5__all->SetBinError(2,0.2125011);
   Btag_Pre_AlphaT_5__all->SetBinError(3,0.4210911);
   Btag_Pre_AlphaT_5__all->SetBinError(4,1.234395);
   Btag_Pre_AlphaT_5__all->SetMinimum(0);
   Btag_Pre_AlphaT_5__all->SetMaximum(2);
   Btag_Pre_AlphaT_5__all->SetEntries(3.517197);
   Btag_Pre_AlphaT_5__all->SetLineWidth(2);
   Btag_Pre_AlphaT_5__all->SetMarkerStyle(20);
   Btag_Pre_AlphaT_5__all->SetMarkerSize(1.5);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetLabelSize(0.12);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitleOffset(1.3);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetTitle("Data/MC");
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetNdivisions(505);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetLabelSize(0.11);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetTitleSize(0.1);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetTitleOffset(0.5);
   Btag_Pre_AlphaT_5__all->Draw("PSAME");
   d->Modified();
   canvasbtag_morethanzero_DiMuon_375_475/Btag_Pre_AlphaT_5__all->cd();
   canvasbtag_morethanzero_DiMuon_375_475/Btag_Pre_AlphaT_5__all->Modified();
   canvasbtag_morethanzero_DiMuon_375_475/Btag_Pre_AlphaT_5__all->cd();
   canvasbtag_morethanzero_DiMuon_375_475/Btag_Pre_AlphaT_5__all->SetSelected(canvasbtag_morethanzero_DiMuon_375_475/Btag_Pre_AlphaT_5__all);
}
