{
//=========Macro generated from canvas: canvasDiMuon_675_775/Btag_Pre_AlphaT_5__all/cannameBtag_Pre_AlphaT_5__all
//=========  (Thu May 10 12:45:51 2012) by ROOT version5.32/00
   TCanvas *canvasDiMuon_675_775/Btag_Pre_AlphaT_5__all = new TCanvas("canvasDiMuon_675_775/Btag_Pre_AlphaT_5__all", "cannameBtag_Pre_AlphaT_5__all",1,1,1200,1176);
   gStyle->SetOptStat(0);
   canvasDiMuon_675_775/Btag_Pre_AlphaT_5__all->SetHighLightColor(2);
   canvasDiMuon_675_775/Btag_Pre_AlphaT_5__all->Range(0,0,1,1);
   canvasDiMuon_675_775/Btag_Pre_AlphaT_5__all->SetFillColor(0);
   canvasDiMuon_675_775/Btag_Pre_AlphaT_5__all->SetBorderMode(0);
   canvasDiMuon_675_775/Btag_Pre_AlphaT_5__all->SetBorderSize(2);
   canvasDiMuon_675_775/Btag_Pre_AlphaT_5__all->SetTickx(1);
   canvasDiMuon_675_775/Btag_Pre_AlphaT_5__all->SetTicky(1);
   canvasDiMuon_675_775/Btag_Pre_AlphaT_5__all->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: u
   TPad *u = new TPad("u", "u",0.01,0.25,0.99,0.99);
   u->Draw();
   u->cd();
   u->Range(-0.7500001,-0.6442211,6.75,2.78769);
   u->SetFillColor(0);
   u->SetBorderMode(0);
   u->SetBorderSize(2);
   u->SetLogy();
   u->SetTickx(1);
   u->SetTicky(1);
   u->SetFrameBorderMode(0);
   u->SetFrameBorderMode(0);
   Double_t xAxis1753[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis1753);
   Btag_Pre_AlphaT_5__all->SetBinContent(1,10);
   Btag_Pre_AlphaT_5__all->SetBinContent(2,4);
   Btag_Pre_AlphaT_5__all->SetBinContent(3,1);
   Btag_Pre_AlphaT_5__all->SetBinError(1,3.162278);
   Btag_Pre_AlphaT_5__all->SetBinError(2,2.3);
   Btag_Pre_AlphaT_5__all->SetBinError(3,1);
   Btag_Pre_AlphaT_5__all->SetMinimum(0.5);
   Btag_Pre_AlphaT_5__all->SetMaximum(278.2907);
   Btag_Pre_AlphaT_5__all->SetEntries(15);
   Btag_Pre_AlphaT_5__all->SetLineWidth(2);
   Btag_Pre_AlphaT_5__all->SetMarkerStyle(20);
   Btag_Pre_AlphaT_5__all->SetMarkerSize(1.5);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("N_{b-tag}");
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitleOffset(1.3);
   Btag_Pre_AlphaT_5__all->Draw("");
   
   THStack * = new THStack();
   ->SetName("");
   ->SetTitle("");
   
   TH1F *_stack_117 = new TH1F("_stack_117","",6,0,6);
   _stack_117->SetMinimum(0.01253755);
   _stack_117->SetMaximum(50.1502);
   _stack_117->SetDirectory(0);
   _stack_117->SetStats(0);
   _stack_117->GetXaxis()->SetLabelFont(42);
   _stack_117->GetXaxis()->SetLabelOffset(0.007);
   _stack_117->GetXaxis()->SetLabelSize(0.05);
   _stack_117->GetXaxis()->SetTitleSize(0.05);
   _stack_117->GetYaxis()->SetLabelFont(42);
   _stack_117->GetYaxis()->SetLabelOffset(0.007);
   _stack_117->GetYaxis()->SetLabelSize(0.05);
   _stack_117->GetZaxis()->SetLabelFont(42);
   _stack_117->GetZaxis()->SetLabelOffset(0.007);
   _stack_117->GetZaxis()->SetLabelSize(0.05);
   ->SetHistogram(_stack_117);
   
   Double_t xAxis1754[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis1754);
   Btag_Pre_AlphaT_5__all->SetFillColor(4);
   Btag_Pre_AlphaT_5__all->SetLineColor(4);
   Btag_Pre_AlphaT_5__all->SetLineWidth(3);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("Number of Btags");
   ->Add(Btag_Pre_AlphaT_5__all,"");
   Double_t xAxis1755[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis1755);
   Btag_Pre_AlphaT_5__all->SetFillColor(5);
   Btag_Pre_AlphaT_5__all->SetLineColor(5);
   Btag_Pre_AlphaT_5__all->SetLineWidth(3);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("Number of Btags");
   ->Add(Btag_Pre_AlphaT_5__all,"");
   Double_t xAxis1756[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis1756);
   Btag_Pre_AlphaT_5__all->SetFillColor(7);
   Btag_Pre_AlphaT_5__all->SetLineColor(7);
   Btag_Pre_AlphaT_5__all->SetLineStyle(10);
   Btag_Pre_AlphaT_5__all->SetLineWidth(3);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("Number of Btags");
   ->Add(Btag_Pre_AlphaT_5__all,"");
   Double_t xAxis1757[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis1757);
   Btag_Pre_AlphaT_5__all->SetBinContent(1,0.07399568);
   Btag_Pre_AlphaT_5__all->SetBinContent(3,0.05662981);
   Btag_Pre_AlphaT_5__all->SetBinError(1,0.05923267);
   Btag_Pre_AlphaT_5__all->SetBinError(3,0.05662981);
   Btag_Pre_AlphaT_5__all->SetEntries(3);
   Btag_Pre_AlphaT_5__all->SetFillColor(40);
   Btag_Pre_AlphaT_5__all->SetLineColor(40);
   Btag_Pre_AlphaT_5__all->SetLineWidth(3);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("Number of Btags");
   ->Add(Btag_Pre_AlphaT_5__all,"");
   Double_t xAxis1758[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis1758);
   Btag_Pre_AlphaT_5__all->SetBinContent(1,0.1583824);
   Btag_Pre_AlphaT_5__all->SetBinContent(2,0.02573598);
   Btag_Pre_AlphaT_5__all->SetBinError(1,0.03984955);
   Btag_Pre_AlphaT_5__all->SetBinError(2,0.01304504);
   Btag_Pre_AlphaT_5__all->SetEntries(24);
   Btag_Pre_AlphaT_5__all->SetFillColor(44);
   Btag_Pre_AlphaT_5__all->SetLineColor(44);
   Btag_Pre_AlphaT_5__all->SetLineWidth(3);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("Number of Btags");
   ->Add(Btag_Pre_AlphaT_5__all,"");
   Double_t xAxis1759[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis1759);
   Btag_Pre_AlphaT_5__all->SetBinContent(2,1.127107);
   Btag_Pre_AlphaT_5__all->SetBinContent(3,0.4152537);
   Btag_Pre_AlphaT_5__all->SetBinError(2,0.5121502);
   Btag_Pre_AlphaT_5__all->SetBinError(3,0.3442289);
   Btag_Pre_AlphaT_5__all->SetEntries(7);
   Btag_Pre_AlphaT_5__all->SetFillColor(2);
   Btag_Pre_AlphaT_5__all->SetLineColor(2);
   Btag_Pre_AlphaT_5__all->SetLineWidth(3);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("Number of Btags");
   ->Add(Btag_Pre_AlphaT_5__all,"");
   Double_t xAxis1760[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis1760);
   Btag_Pre_AlphaT_5__all->SetBinContent(1,27.59669);
   Btag_Pre_AlphaT_5__all->SetBinContent(2,2.116491);
   Btag_Pre_AlphaT_5__all->SetBinContent(3,0.522069);
   Btag_Pre_AlphaT_5__all->SetBinError(1,3.747184);
   Btag_Pre_AlphaT_5__all->SetBinError(2,1.000485);
   Btag_Pre_AlphaT_5__all->SetBinError(3,0.522069);
   Btag_Pre_AlphaT_5__all->SetEntries(72);
   Btag_Pre_AlphaT_5__all->SetFillColor(6);
   Btag_Pre_AlphaT_5__all->SetLineColor(6);
   Btag_Pre_AlphaT_5__all->SetLineWidth(3);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("Number of Btags");
   ->Add(Btag_Pre_AlphaT_5__all,"");
   ->Draw("histsame");
   
   TLegend *leg = new TLegend(0.68,0.53,0.9,0.75,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.02);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("Btag_Pre_AlphaT_5__all","Data","P");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.5);
   entry=leg->AddEntry("Btag_Pre_AlphaT_5__all","W + Jets","L");
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Btag_Pre_AlphaT_5__all","t\bar{t}","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Btag_Pre_AlphaT_5__all","Z\rightarrow \nu\bar{\nu}","L");
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Btag_Pre_AlphaT_5__all","DY + Jets","L");
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Btag_Pre_AlphaT_5__all","Single Top","L");
   entry->SetLineColor(40);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Btag_Pre_AlphaT_5__all","WW/ZZ/WZ","L");
   entry->SetLineColor(44);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Btag_Pre_AlphaT_5__all","QCD","L");
   entry->SetLineColor(7);
   entry->SetLineStyle(10);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   Double_t xAxis1761[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis1761);
   Btag_Pre_AlphaT_5__all->SetBinContent(1,10);
   Btag_Pre_AlphaT_5__all->SetBinContent(2,4);
   Btag_Pre_AlphaT_5__all->SetBinContent(3,1);
   Btag_Pre_AlphaT_5__all->SetBinError(1,3.162278);
   Btag_Pre_AlphaT_5__all->SetBinError(2,2.3);
   Btag_Pre_AlphaT_5__all->SetBinError(3,1);
   Btag_Pre_AlphaT_5__all->SetMinimum(0.5);
   Btag_Pre_AlphaT_5__all->SetMaximum(278.2907);
   Btag_Pre_AlphaT_5__all->SetEntries(15);
   Btag_Pre_AlphaT_5__all->SetLineWidth(2);
   Btag_Pre_AlphaT_5__all->SetMarkerStyle(20);
   Btag_Pre_AlphaT_5__all->SetMarkerSize(1.5);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("N_{b-tag}");
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitleOffset(1.3);
   Btag_Pre_AlphaT_5__all->Draw("PSAME");
   TLatex *   tex = new TLatex(0.1,0.95,"DiMuon_675_775    Jet Multiplicity=all");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.6,0.85,"CMS Preliminary 2012, 7TeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.6,0.79,"\int L dt = 5.0 fb^{-1}");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   u->Modified();
   canvasDiMuon_675_775/Btag_Pre_AlphaT_5__all->cd();
  
// ------------>Primitives in pad: d
   d = new TPad("d", "d",0.01,0.01,0.99,0.25);
   d->Draw();
   d->cd();
   d->Range(-0.7500001,-0.25,6.75,2.25);
   d->SetFillColor(0);
   d->SetBorderMode(0);
   d->SetBorderSize(2);
   d->SetTickx(1);
   d->SetTicky(1);
   d->SetFrameBorderMode(0);
   d->SetFrameBorderMode(0);
   Double_t xAxis1762[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis1762);
   Btag_Pre_AlphaT_5__all->SetBinContent(1,0.3593365);
   Btag_Pre_AlphaT_5__all->SetBinContent(2,1.223491);
   Btag_Pre_AlphaT_5__all->SetBinContent(3,1.006084);
   Btag_Pre_AlphaT_5__all->SetBinError(1,0.3437109);
   Btag_Pre_AlphaT_5__all->SetBinError(2,0.6699476);
   Btag_Pre_AlphaT_5__all->SetBinError(3,1.182822);
   Btag_Pre_AlphaT_5__all->SetMinimum(0);
   Btag_Pre_AlphaT_5__all->SetMaximum(2);
   Btag_Pre_AlphaT_5__all->SetEntries(3.186693);
   Btag_Pre_AlphaT_5__all->SetLineWidth(2);
   Btag_Pre_AlphaT_5__all->SetMarkerStyle(20);
   Btag_Pre_AlphaT_5__all->SetMarkerSize(1.5);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetLabelSize(0.12);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitleOffset(1.3);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetTitle("Data/MC");
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetNdivisions(505);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetLabelSize(0.11);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetTitleSize(0.1);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetTitleOffset(0.5);
   Btag_Pre_AlphaT_5__all->Draw("P");
   
   TGraphErrors *gre = new TGraphErrors(6);
   gre->SetName("Graph_from_Btag_Pre_AlphaT_5__all");
   gre->SetTitle("");
   gre->SetFillColor(17);
   gre->SetFillStyle(3244);
   gre->SetLineWidth(2);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.5);
   gre->SetPoint(0,0.5,1);
   gre->SetPointError(0,0.5,0.1346744);
   gre->SetPoint(1,1.5,1);
   gre->SetPointError(1,0.5,0.3438093);
   gre->SetPoint(2,2.5,1);
   gre->SetPointError(2,0.5,0.6317188);
   gre->SetPoint(3,3.5,1);
   gre->SetPointError(3,0.5,0);
   gre->SetPoint(4,4.5,1);
   gre->SetPointError(4,0.5,0);
   gre->SetPoint(5,5.5,1);
   gre->SetPointError(5,0.5,0);
   
   TH1F *Graph_Graph_from_Btag_Pre_AlphaT_5__all294 = new TH1F("Graph_Graph_from_Btag_Pre_AlphaT_5__all294","",100,0,6.6);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all294->SetMinimum(0.2419374);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all294->SetMaximum(1.758063);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all294->SetDirectory(0);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all294->SetStats(0);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all294->GetXaxis()->SetLabelFont(42);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all294->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all294->GetXaxis()->SetLabelSize(0.05);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all294->GetXaxis()->SetTitleSize(0.05);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all294->GetYaxis()->SetLabelFont(42);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all294->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all294->GetYaxis()->SetLabelSize(0.05);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all294->GetZaxis()->SetLabelFont(42);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all294->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all294->GetZaxis()->SetLabelSize(0.05);
   gre->SetHistogram(Graph_Graph_from_Btag_Pre_AlphaT_5__all294);
   
   gre->Draw("2");
   TLine *line = new TLine(0,1,6,1);
   line->SetLineWidth(3);
   line->Draw();
   Double_t xAxis1763[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis1763);
   Btag_Pre_AlphaT_5__all->SetBinContent(1,0.3593365);
   Btag_Pre_AlphaT_5__all->SetBinContent(2,1.223491);
   Btag_Pre_AlphaT_5__all->SetBinContent(3,1.006084);
   Btag_Pre_AlphaT_5__all->SetBinError(1,0.3437109);
   Btag_Pre_AlphaT_5__all->SetBinError(2,0.6699476);
   Btag_Pre_AlphaT_5__all->SetBinError(3,1.182822);
   Btag_Pre_AlphaT_5__all->SetMinimum(0);
   Btag_Pre_AlphaT_5__all->SetMaximum(2);
   Btag_Pre_AlphaT_5__all->SetEntries(3.186693);
   Btag_Pre_AlphaT_5__all->SetLineWidth(2);
   Btag_Pre_AlphaT_5__all->SetMarkerStyle(20);
   Btag_Pre_AlphaT_5__all->SetMarkerSize(1.5);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetLabelSize(0.12);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitleOffset(1.3);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetTitle("Data/MC");
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetNdivisions(505);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetLabelSize(0.11);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetTitleSize(0.1);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetTitleOffset(0.5);
   Btag_Pre_AlphaT_5__all->Draw("PSAME");
   d->Modified();
   canvasDiMuon_675_775/Btag_Pre_AlphaT_5__all->cd();
   canvasDiMuon_675_775/Btag_Pre_AlphaT_5__all->Modified();
   canvasDiMuon_675_775/Btag_Pre_AlphaT_5__all->cd();
   canvasDiMuon_675_775/Btag_Pre_AlphaT_5__all->SetSelected(canvasDiMuon_675_775/Btag_Pre_AlphaT_5__all);
}
