{
//=========Macro generated from canvas: canvasbtag_morethanzero_DiMuon_325_375/Btag_Pre_AlphaT_5__all/cannameBtag_Pre_AlphaT_5__all
//=========  (Thu May 10 12:48:17 2012) by ROOT version5.32/00
   TCanvas *canvasbtag_morethanzero_DiMuon_325_375/Btag_Pre_AlphaT_5__all = new TCanvas("canvasbtag_morethanzero_DiMuon_325_375/Btag_Pre_AlphaT_5__all", "cannameBtag_Pre_AlphaT_5__all",1,1,1200,1176);
   gStyle->SetOptStat(0);
   canvasbtag_morethanzero_DiMuon_325_375/Btag_Pre_AlphaT_5__all->SetHighLightColor(2);
   canvasbtag_morethanzero_DiMuon_325_375/Btag_Pre_AlphaT_5__all->Range(0,0,1,1);
   canvasbtag_morethanzero_DiMuon_325_375/Btag_Pre_AlphaT_5__all->SetFillColor(0);
   canvasbtag_morethanzero_DiMuon_325_375/Btag_Pre_AlphaT_5__all->SetBorderMode(0);
   canvasbtag_morethanzero_DiMuon_325_375/Btag_Pre_AlphaT_5__all->SetBorderSize(2);
   canvasbtag_morethanzero_DiMuon_325_375/Btag_Pre_AlphaT_5__all->SetTickx(1);
   canvasbtag_morethanzero_DiMuon_325_375/Btag_Pre_AlphaT_5__all->SetTicky(1);
   canvasbtag_morethanzero_DiMuon_325_375/Btag_Pre_AlphaT_5__all->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: u
   TPad *u = new TPad("u", "u",0.01,0.25,0.99,0.99);
   u->Draw();
   u->cd();
   u->Range(-0.7500001,-0.6678884,6.75,3.000696);
   u->SetFillColor(0);
   u->SetBorderMode(0);
   u->SetBorderSize(2);
   u->SetLogy();
   u->SetTickx(1);
   u->SetTicky(1);
   u->SetFrameBorderMode(0);
   u->SetFrameBorderMode(0);
   Double_t xAxis6433[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis6433);
   Btag_Pre_AlphaT_5__all->SetBinContent(2,13);
   Btag_Pre_AlphaT_5__all->SetBinContent(3,3);
   Btag_Pre_AlphaT_5__all->SetBinError(2,3.605551);
   Btag_Pre_AlphaT_5__all->SetBinError(3,2.14);
   Btag_Pre_AlphaT_5__all->SetMinimum(0.5);
   Btag_Pre_AlphaT_5__all->SetMaximum(430.3653);
   Btag_Pre_AlphaT_5__all->SetEntries(16);
   Btag_Pre_AlphaT_5__all->SetLineWidth(2);
   Btag_Pre_AlphaT_5__all->SetMarkerStyle(20);
   Btag_Pre_AlphaT_5__all->SetMarkerSize(1.5);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("N_{b-tag}");
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitleOffset(1.3);
   Btag_Pre_AlphaT_5__all->Draw("");
   
   THStack * = new THStack();
   ->SetName("");
   ->SetTitle("");
   
   TH1F *_stack_429 = new TH1F("_stack_429","",6,0,6);
   _stack_429->SetMinimum(0.01721461);
   _stack_429->SetMaximum(68.85845);
   _stack_429->SetDirectory(0);
   _stack_429->SetStats(0);
   _stack_429->GetXaxis()->SetLabelFont(42);
   _stack_429->GetXaxis()->SetLabelOffset(0.007);
   _stack_429->GetXaxis()->SetLabelSize(0.05);
   _stack_429->GetXaxis()->SetTitleSize(0.05);
   _stack_429->GetYaxis()->SetLabelFont(42);
   _stack_429->GetYaxis()->SetLabelOffset(0.007);
   _stack_429->GetYaxis()->SetLabelSize(0.05);
   _stack_429->GetZaxis()->SetLabelFont(42);
   _stack_429->GetZaxis()->SetLabelOffset(0.007);
   _stack_429->GetZaxis()->SetLabelSize(0.05);
   ->SetHistogram(_stack_429);
   
   Double_t xAxis6434[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis6434);
   Btag_Pre_AlphaT_5__all->SetFillColor(4);
   Btag_Pre_AlphaT_5__all->SetLineColor(4);
   Btag_Pre_AlphaT_5__all->SetLineWidth(3);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("Number of Btags");
   ->Add(Btag_Pre_AlphaT_5__all,"");
   Double_t xAxis6435[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis6435);
   Btag_Pre_AlphaT_5__all->SetFillColor(5);
   Btag_Pre_AlphaT_5__all->SetLineColor(5);
   Btag_Pre_AlphaT_5__all->SetLineWidth(3);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("Number of Btags");
   ->Add(Btag_Pre_AlphaT_5__all,"");
   Double_t xAxis6436[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis6436);
   Btag_Pre_AlphaT_5__all->SetFillColor(7);
   Btag_Pre_AlphaT_5__all->SetLineColor(7);
   Btag_Pre_AlphaT_5__all->SetLineStyle(10);
   Btag_Pre_AlphaT_5__all->SetLineWidth(3);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("Number of Btags");
   ->Add(Btag_Pre_AlphaT_5__all,"");
   Double_t xAxis6437[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis6437);
   Btag_Pre_AlphaT_5__all->SetBinContent(2,0.3912058);
   Btag_Pre_AlphaT_5__all->SetBinContent(3,0.07900873);
   Btag_Pre_AlphaT_5__all->SetBinContent(4,0.006689987);
   Btag_Pre_AlphaT_5__all->SetBinError(2,0.06313323);
   Btag_Pre_AlphaT_5__all->SetBinError(3,0.02194279);
   Btag_Pre_AlphaT_5__all->SetBinError(4,0.006689987);
   Btag_Pre_AlphaT_5__all->SetEntries(66);
   Btag_Pre_AlphaT_5__all->SetFillColor(44);
   Btag_Pre_AlphaT_5__all->SetLineColor(44);
   Btag_Pre_AlphaT_5__all->SetLineWidth(3);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("Number of Btags");
   ->Add(Btag_Pre_AlphaT_5__all,"");
   Double_t xAxis6438[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis6438);
   Btag_Pre_AlphaT_5__all->SetBinContent(2,0.3781895);
   Btag_Pre_AlphaT_5__all->SetBinContent(3,0.2719716);
   Btag_Pre_AlphaT_5__all->SetBinError(2,0.1425133);
   Btag_Pre_AlphaT_5__all->SetBinError(3,0.1143206);
   Btag_Pre_AlphaT_5__all->SetEntries(18);
   Btag_Pre_AlphaT_5__all->SetFillColor(40);
   Btag_Pre_AlphaT_5__all->SetLineColor(40);
   Btag_Pre_AlphaT_5__all->SetLineWidth(3);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("Number of Btags");
   ->Add(Btag_Pre_AlphaT_5__all,"");
   Double_t xAxis6439[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis6439);
   Btag_Pre_AlphaT_5__all->SetBinContent(2,9.390816);
   Btag_Pre_AlphaT_5__all->SetBinContent(3,8.027337);
   Btag_Pre_AlphaT_5__all->SetBinError(2,1.764723);
   Btag_Pre_AlphaT_5__all->SetBinError(3,1.942259);
   Btag_Pre_AlphaT_5__all->SetEntries(80);
   Btag_Pre_AlphaT_5__all->SetFillColor(2);
   Btag_Pre_AlphaT_5__all->SetLineColor(2);
   Btag_Pre_AlphaT_5__all->SetLineWidth(3);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("Number of Btags");
   ->Add(Btag_Pre_AlphaT_5__all,"");
   Double_t xAxis6440[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis6440);
   Btag_Pre_AlphaT_5__all->SetBinContent(2,32.87632);
   Btag_Pre_AlphaT_5__all->SetBinContent(3,7.184199);
   Btag_Pre_AlphaT_5__all->SetBinError(2,4.06356);
   Btag_Pre_AlphaT_5__all->SetBinError(3,4.880163);
   Btag_Pre_AlphaT_5__all->SetEntries(90);
   Btag_Pre_AlphaT_5__all->SetFillColor(6);
   Btag_Pre_AlphaT_5__all->SetLineColor(6);
   Btag_Pre_AlphaT_5__all->SetLineWidth(3);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("Number of Btags");
   ->Add(Btag_Pre_AlphaT_5__all,"");
   ->Draw("histsame");
   
   TLegend *leg = new TLegend(0.68,0.53,0.9,0.75,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.02);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("Btag_Pre_AlphaT_5__all","Data","P");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.5);
   entry=leg->AddEntry("Btag_Pre_AlphaT_5__all","W + Jets","L");
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Btag_Pre_AlphaT_5__all","t\bar{t}","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Btag_Pre_AlphaT_5__all","Z\rightarrow \nu\bar{\nu}","L");
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Btag_Pre_AlphaT_5__all","DY + Jets","L");
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Btag_Pre_AlphaT_5__all","Single Top","L");
   entry->SetLineColor(40);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Btag_Pre_AlphaT_5__all","WW/ZZ/WZ","L");
   entry->SetLineColor(44);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Btag_Pre_AlphaT_5__all","QCD","L");
   entry->SetLineColor(7);
   entry->SetLineStyle(10);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   Double_t xAxis6441[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis6441);
   Btag_Pre_AlphaT_5__all->SetBinContent(2,13);
   Btag_Pre_AlphaT_5__all->SetBinContent(3,3);
   Btag_Pre_AlphaT_5__all->SetBinError(2,3.605551);
   Btag_Pre_AlphaT_5__all->SetBinError(3,2.14);
   Btag_Pre_AlphaT_5__all->SetMinimum(0.5);
   Btag_Pre_AlphaT_5__all->SetMaximum(430.3653);
   Btag_Pre_AlphaT_5__all->SetEntries(16);
   Btag_Pre_AlphaT_5__all->SetLineWidth(2);
   Btag_Pre_AlphaT_5__all->SetMarkerStyle(20);
   Btag_Pre_AlphaT_5__all->SetMarkerSize(1.5);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitle("N_{b-tag}");
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitleOffset(1.3);
   Btag_Pre_AlphaT_5__all->Draw("PSAME");
   TLatex *   tex = new TLatex(0.1,0.95,"btag_morethanzero_DiMuon_325_375    Jet Multiplicity=all");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.6,0.85,"CMS Preliminary 2012, 7TeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.6,0.79,"\int L dt = 5.0 fb^{-1}");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   u->Modified();
   canvasbtag_morethanzero_DiMuon_325_375/Btag_Pre_AlphaT_5__all->cd();
  
// ------------>Primitives in pad: d
   d = new TPad("d", "d",0.01,0.01,0.99,0.25);
   d->Draw();
   d->cd();
   d->Range(-0.7500001,-0.25,6.75,2.25);
   d->SetFillColor(0);
   d->SetBorderMode(0);
   d->SetBorderSize(2);
   d->SetTickx(1);
   d->SetTicky(1);
   d->SetFrameBorderMode(0);
   d->SetFrameBorderMode(0);
   Double_t xAxis6442[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis6442);
   Btag_Pre_AlphaT_5__all->SetBinContent(2,0.3020689);
   Btag_Pre_AlphaT_5__all->SetBinContent(3,0.1927709);
   Btag_Pre_AlphaT_5__all->SetBinError(2,0.2958597);
   Btag_Pre_AlphaT_5__all->SetBinError(3,0.7891841);
   Btag_Pre_AlphaT_5__all->SetMinimum(0);
   Btag_Pre_AlphaT_5__all->SetMaximum(2);
   Btag_Pre_AlphaT_5__all->SetEntries(7.865663);
   Btag_Pre_AlphaT_5__all->SetLineWidth(2);
   Btag_Pre_AlphaT_5__all->SetMarkerStyle(20);
   Btag_Pre_AlphaT_5__all->SetMarkerSize(1.5);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetLabelSize(0.12);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitleOffset(1.3);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetTitle("Data/MC");
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetNdivisions(505);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetLabelSize(0.11);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetTitleSize(0.1);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetTitleOffset(0.5);
   Btag_Pre_AlphaT_5__all->Draw("P");
   
   TGraphErrors *gre = new TGraphErrors(6);
   gre->SetName("Graph_from_Btag_Pre_AlphaT_5__all");
   gre->SetTitle("");
   gre->SetFillColor(17);
   gre->SetFillStyle(3244);
   gre->SetLineWidth(2);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.5);
   gre->SetPoint(0,0.5,1);
   gre->SetPointError(0,0.5,0);
   gre->SetPoint(1,1.5,1);
   gre->SetPointError(1,0.5,0.1030044);
   gre->SetPoint(2,2.5,1);
   gre->SetPointError(2,0.5,0.3375902);
   gre->SetPoint(3,3.5,1);
   gre->SetPointError(3,0.5,1);
   gre->SetPoint(4,4.5,1);
   gre->SetPointError(4,0.5,0);
   gre->SetPoint(5,5.5,1);
   gre->SetPointError(5,0.5,0);
   
   TH1F *Graph_Graph_from_Btag_Pre_AlphaT_5__all1074 = new TH1F("Graph_Graph_from_Btag_Pre_AlphaT_5__all1074","",100,0,6.6);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all1074->SetMinimum(0);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all1074->SetMaximum(2.2);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all1074->SetDirectory(0);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all1074->SetStats(0);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all1074->GetXaxis()->SetLabelFont(42);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all1074->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all1074->GetXaxis()->SetLabelSize(0.05);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all1074->GetXaxis()->SetTitleSize(0.05);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all1074->GetYaxis()->SetLabelFont(42);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all1074->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all1074->GetYaxis()->SetLabelSize(0.05);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all1074->GetZaxis()->SetLabelFont(42);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all1074->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph_from_Btag_Pre_AlphaT_5__all1074->GetZaxis()->SetLabelSize(0.05);
   gre->SetHistogram(Graph_Graph_from_Btag_Pre_AlphaT_5__all1074);
   
   gre->Draw("2");
   TLine *line = new TLine(0,1,6,1);
   line->SetLineWidth(3);
   line->Draw();
   Double_t xAxis6443[7] = {0, 1, 2, 3, 4, 5, 6}; 
   
   TH1D *Btag_Pre_AlphaT_5__all = new TH1D("Btag_Pre_AlphaT_5__all","",6, xAxis6443);
   Btag_Pre_AlphaT_5__all->SetBinContent(2,0.3020689);
   Btag_Pre_AlphaT_5__all->SetBinContent(3,0.1927709);
   Btag_Pre_AlphaT_5__all->SetBinError(2,0.2958597);
   Btag_Pre_AlphaT_5__all->SetBinError(3,0.7891841);
   Btag_Pre_AlphaT_5__all->SetMinimum(0);
   Btag_Pre_AlphaT_5__all->SetMaximum(2);
   Btag_Pre_AlphaT_5__all->SetEntries(7.865663);
   Btag_Pre_AlphaT_5__all->SetLineWidth(2);
   Btag_Pre_AlphaT_5__all->SetMarkerStyle(20);
   Btag_Pre_AlphaT_5__all->SetMarkerSize(1.5);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetLabelSize(0.12);
   Btag_Pre_AlphaT_5__all->GetXaxis()->SetTitleOffset(1.3);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetTitle("Data/MC");
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetNdivisions(505);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetLabelSize(0.11);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetTitleSize(0.1);
   Btag_Pre_AlphaT_5__all->GetYaxis()->SetTitleOffset(0.5);
   Btag_Pre_AlphaT_5__all->Draw("PSAME");
   d->Modified();
   canvasbtag_morethanzero_DiMuon_325_375/Btag_Pre_AlphaT_5__all->cd();
   canvasbtag_morethanzero_DiMuon_325_375/Btag_Pre_AlphaT_5__all->Modified();
   canvasbtag_morethanzero_DiMuon_325_375/Btag_Pre_AlphaT_5__all->cd();
   canvasbtag_morethanzero_DiMuon_325_375/Btag_Pre_AlphaT_5__all->SetSelected(canvasbtag_morethanzero_DiMuon_325_375/Btag_Pre_AlphaT_5__all);
}
